# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
ad1 = np.array([1,2,3,4,5])
print("1 Dimensional array : ", ad1)
# Create a 2-dimensional NumPy array using np.array()
ad2 = np.array([[10,20,30,40,50],[15,25,35,45,55],[1,2,3,4,5]])
print("2 Dimensional array : ")
print(ad2)

1 Dimensional array :  [1 2 3 4 5]
2 Dimensional array : 
[[10 20 30 40 50]
 [15 25 35 45 55]
 [ 1  2  3  4  5]]


In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
ad1.shape, ad1.ndim, ad1.dtype, ad1.size, type(ad1)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
ad2.shape, ad2.ndim, ad2.dtype, ad2.size, type(ad2)

((3, 5), 2, dtype('int32'), 15, numpy.ndarray)

In [5]:
# Create an array of shape (5, 5) with only ones
aones = np.ones((5,5))
aones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
azeros = np.zeros((3,3,5))
azeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arandint = np.random.randint(10,size=(7,2))
arandint

array([[2, 1],
       [1, 3],
       [4, 6],
       [9, 6],
       [2, 1],
       [5, 6],
       [1, 2]])

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
aranflt = np.random.random((3,5))
aranflt

array([[0.58275151, 0.3341761 , 0.83623018, 0.72886937, 0.03621376],
       [0.22939851, 0.23187765, 0.52039182, 0.85473318, 0.8674569 ],
       [0.68691693, 0.38948096, 0.61953116, 0.45977181, 0.23308611]])

In [9]:
# Create an array of normally distributed random numbers
anormal = np.random.normal(1,10,50)
anormal

array([  9.12355777,   5.55013524,   2.66823388,  12.17385086,
        10.95193398, -15.48576207,   3.88295752,   7.42328913,
       -20.65151242,  -1.00555626, -10.35637374,   6.23597758,
         0.11100293,  26.49069092,  13.87655519,  -4.41551726,
       -10.59974617,   9.56199238,   2.45136024,  -6.15570097,
        20.19480982,   0.84627966,   5.76264051,   6.84468431,
         4.02608393,  -2.34336086, -21.81643312,   9.810085  ,
         4.96716006,   8.85647245,  12.76830371,  -2.03291427,
        10.61109629, -14.62707655,   4.87027654,  -0.6543477 ,
         5.43834159,  -7.83334739,  -4.00075498,   7.69196867,
         4.09240946,   1.92802965,  16.51417118,  -1.42763008,
        22.53222752,  -3.04595019, -10.33009054,  -5.42017078,
        -6.58595477,  -6.88571963])

In [10]:
# Set the random seed to 42
npseed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arandom = np.random.randint(10,size = (4,6))
arandom

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [11]:
# Copy the code from the cell above and run it again
npseed = np.random.seed(42)
arandom = np.random.randint(10,size = (4,6))
arandom

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
# Find the 0'th index of the latest array you created
arandom[0]

array([6, 3, 7, 4, 6, 9])

In [13]:
# Get the first 2 rows of latest array you created
arandom[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [15]:
# Get the first 2 values of the first 2 rows of the latest array
arandom[:2,:2]

array([[6, 3],
       [2, 6]])

In [16]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
aran10 = np.random.randint(10,size=(3,5))
aones10 = np.ones((3,5))
aran10,aones10

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
# Add the two arrays together
aran10+aones10

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
aones53 = np.ones((5,3))
aones53

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
aran10+aones53

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
# Do the same operation you just did but this time with a transpose on one array
a = aran10+aones53.T
a

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [22]:
# Take the latest array to the power of 2 using the python way
a ** 2

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [23]:
# Do the same thing with numpy way
np.power(a,2)

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [24]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(a),np.min(a),np.max(a),np.std(a),np.var(a)

(5.6, 1.0, 10.0, 2.8000000000000003, 7.840000000000002)

In [25]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(10,size=(3,3))
b2 = np.random.randint(10,size=(3,2))
b1,b2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]), array([[6, 7],
        [2, 0],
        [3, 1]]))

In [26]:
# Perform a dot product on the two newest arrays you created
np.dot(b1,b2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [27]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
c1 = np.random.randint(10,size=(4,3))
c2 = np.random.randint(10,size=(4,3))
c1,c2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]), array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [28]:
# Perform a hadamard product on the two newest arrays you created
c1*c2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [29]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(c1,c2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [30]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(c1.T,c2)

array([[145, 168, 155],
       [ 63,  84,  81],
       [157, 146, 121]])

In [31]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
d1 = np.random.randint(10,size=(2,3))
d2 = np.random.randint(10,size=(2,3))
d1,d2

(array([[0, 8, 6],
        [8, 7, 0]]), array([[7, 7, 2],
        [0, 7, 2]]))

In [32]:
# Compare the two arrays with '>', '<=' and '==' 
d1>d2

array([[False,  True,  True],
       [ True, False, False]])

In [33]:
d1<=d2

array([[ True, False, False],
       [False,  True,  True]])

In [34]:
d1==d2

array([[False, False, False],
       [False,  True, False]])

In [35]:
# Sort one of the arrays you just created in ascending order
np.sort(d1)

array([[0, 6, 8],
       [0, 7, 8]])

In [36]:
# Sort the indexes of one of the arrays you just created
np.argsort(d1)

array([[0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [37]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(d1)

1

In [38]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [39]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(d1,axis = 1)

array([1, 0], dtype=int64)

In [40]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(d1,axis = 0)

array([0, 1, 1], dtype=int64)